################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
D:/THUC\ TAP\ LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/Ucglib.c \
D:/THUC\ TAP\ LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_bitmap.c \
D:/THUC\ TAP\ LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_box.c \
D:/THUC\ TAP\ LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_ccs.c \
D:/THUC\ TAP\ LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_circle.c \
D:/THUC\ TAP\ LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_clip.c \
D:/THUC\ TAP\ LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_com_msg_api.c \
D:/THUC\ TAP\ LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_default_cb.c \
D:/THUC\ TAP\ LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_ic_st7735.c \
D:/THUC\ TAP\ LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_msg_api.c \
D:/THUC\ TAP\ LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_tft_128x128_st7735.c \
D:/THUC\ TAP\ LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_font.c \
D:/THUC\ TAP\ LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_init.c \
D:/THUC\ TAP\ LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_line.c \
D:/THUC\ TAP\ LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_pixel.c \
D:/THUC\ TAP\ LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_pixel_font_data.c \
D:/THUC\ TAP\ LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_polygon.c \
D:/THUC\ TAP\ LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_rotate.c \
D:/THUC\ TAP\ LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_scale.c \
D:/THUC\ TAP\ LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_vector_font_data.c 

OBJS += \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/Ucglib.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_bitmap.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_box.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_ccs.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_circle.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_clip.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_com_msg_api.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_default_cb.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_ic_st7735.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_msg_api.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_tft_128x128_st7735.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_font.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_init.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_line.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_pixel.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_pixel_font_data.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_polygon.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_rotate.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_scale.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_vector_font_data.o 

C_DEPS += \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/Ucglib.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_bitmap.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_box.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_ccs.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_circle.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_clip.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_com_msg_api.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_default_cb.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_ic_st7735.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_msg_api.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_tft_128x128_st7735.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_font.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_init.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_line.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_pixel.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_pixel_font_data.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_polygon.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_rotate.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_scale.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_vector_font_data.d 


# Each subdirectory must supply rules for building sources it contributes
SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/Ucglib.o: D:/THUC\ TAP\ LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/Ucglib.c SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/utils" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_bitmap.o: D:/THUC\ TAP\ LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_bitmap.c SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/utils" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_box.o: D:/THUC\ TAP\ LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_box.c SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/utils" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_ccs.o: D:/THUC\ TAP\ LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_ccs.c SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/utils" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_circle.o: D:/THUC\ TAP\ LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_circle.c SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/utils" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_clip.o: D:/THUC\ TAP\ LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_clip.c SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/utils" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_com_msg_api.o: D:/THUC\ TAP\ LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_com_msg_api.c SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/utils" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_default_cb.o: D:/THUC\ TAP\ LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_default_cb.c SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/utils" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_ic_st7735.o: D:/THUC\ TAP\ LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_ic_st7735.c SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/utils" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_msg_api.o: D:/THUC\ TAP\ LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_msg_api.c SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/utils" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_tft_128x128_st7735.o: D:/THUC\ TAP\ LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_tft_128x128_st7735.c SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/utils" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_font.o: D:/THUC\ TAP\ LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_font.c SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/utils" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_init.o: D:/THUC\ TAP\ LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_init.c SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/utils" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_line.o: D:/THUC\ TAP\ LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_line.c SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/utils" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_pixel.o: D:/THUC\ TAP\ LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_pixel.c SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/utils" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_pixel_font_data.o: D:/THUC\ TAP\ LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_pixel_font_data.c SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/utils" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_polygon.o: D:/THUC\ TAP\ LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_polygon.c SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/utils" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_rotate.o: D:/THUC\ TAP\ LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_rotate.c SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/utils" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_scale.o: D:/THUC\ TAP\ LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_scale.c SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/utils" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_vector_font_data.o: D:/THUC\ TAP\ LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_vector_font_data.c SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -I"D:/THUC TAP LUMI/thu-vien/SDK_1.0.3_NUCLEO-F401RE/shared/utils" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"

clean: clean-SDK_1-2e-0-2e-3_NUCLEO-2d-F401RE-2f-shared-2f-Middle-2f-ucglib

clean-SDK_1-2e-0-2e-3_NUCLEO-2d-F401RE-2f-shared-2f-Middle-2f-ucglib:
	-$(RM) ./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/Ucglib.d ./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/Ucglib.o ./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_bitmap.d ./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_bitmap.o ./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_box.d ./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_box.o ./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_ccs.d ./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_ccs.o ./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_circle.d ./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_circle.o ./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_clip.d ./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_clip.o ./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_com_msg_api.d ./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_com_msg_api.o ./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_default_cb.d ./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_default_cb.o ./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_ic_st7735.d ./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_ic_st7735.o ./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_msg_api.d ./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_msg_api.o ./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_tft_128x128_st7735.d ./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_dev_tft_128x128_st7735.o ./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_font.d ./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_font.o ./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_init.d ./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_init.o ./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_line.d ./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_line.o ./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_pixel.d ./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_pixel.o ./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_pixel_font_data.d ./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_pixel_font_data.o ./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_polygon.d ./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_polygon.o ./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_rotate.d ./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_rotate.o ./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_scale.d ./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_scale.o ./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_vector_font_data.d ./SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib/ucg_vector_font_data.o

.PHONY: clean-SDK_1-2e-0-2e-3_NUCLEO-2d-F401RE-2f-shared-2f-Middle-2f-ucglib

